mock prover hide duplicate errors (#354)
Currently, since we are adding a duplicate instance at the end, this
causes duplicate errors and sometimes it can be a lot of errors. This PR
attempts to cover the current case where if two consecutive errors are
identical then hide the duplicate.

```
======================================================

AssertZeroError ....

Error: 2 constraints not satisfied (1 duplicates hidden)
======================================================
```