Enable clippy check for `Cargo.toml` files (#401)
One of the benefits is that we get warned, when we depend on multiple
version of the same crate. That's inefficient and can lead to subtle
errors.

As an example, you can run this to see the different versions of `syn`:

```console
$ cargo tree --invert  syn
error: There are multiple `syn` packages in your project, and the specification `syn` is ambiguous.
Please re-run this command with one of the following specifications:
  syn@1.0.109
  syn@2.0.79
```

And then be more specific to see the offenders that still depend on the
old version of `syn`:

```console
$ cargo tree --invert syn@1
syn v1.0.109
└── unroll v0.1.5 (proc-macro)
    ├── plonky2 v0.2.2
    │   └── mpcs v0.1.0 (/home/matthias/scroll/prog/ceno6/mpcs)
    │       └── ceno_zkvm v0.1.0 (/home/matthias/scroll/prog/ceno6/ceno_zkvm)
    │   [dev-dependencies]
    │   └── poseidon v0.1.0 (/home/matthias/scroll/prog/ceno6/poseidon)
    │       ├── ff_ext v0.1.0 (/home/matthias/scroll/prog/ceno6/ff_ext)
    │       │   ├── ceno_zkvm v0.1.0 (/home/matthias/scroll/prog/ceno6/ceno_zkvm)
    │       │   ├── mpcs v0.1.0 (/home/matthias/scroll/prog/ceno6/mpcs) (*)
    │       │   ├── multilinear_extensions v0.1.0 (/home/matthias/scroll/prog/ceno6/multilinear_extensions)
    │       │   │   ├── ceno_zkvm v0.1.0 (/home/matthias/scroll/prog/ceno6/ceno_zkvm)
    │       │   │   ├── mpcs v0.1.0 (/home/matthias/scroll/prog/ceno6/mpcs) (*)
    │       │   │   └── sumcheck v0.1.0 (/home/matthias/scroll/prog/ceno6/sumcheck)
    │       │   │       └── ceno_zkvm v0.1.0 (/home/matthias/scroll/prog/ceno6/ceno_zkvm)
    │       │   ├── sumcheck v0.1.0 (/home/matthias/scroll/prog/ceno6/sumcheck) (*)
    │       │   └── transcript v0.1.0 (/home/matthias/scroll/prog/ceno6/transcript)
    │       │       ├── ceno_zkvm v0.1.0 (/home/matthias/scroll/prog/ceno6/ceno_zkvm)
    │       │       ├── mpcs v0.1.0 (/home/matthias/scroll/prog/ceno6/mpcs) (*)
    │       │       └── sumcheck v0.1.0 (/home/matthias/scroll/prog/ceno6/sumcheck) (*)
    │       ├── mpcs v0.1.0 (/home/matthias/scroll/prog/ceno6/mpcs) (*)
    │       └── transcript v0.1.0 (/home/matthias/scroll/prog/ceno6/transcript) (*)
    ├── plonky2_field v0.2.2
    │   └── plonky2 v0.2.2 (*)
    └── poseidon v0.1.0 (/home/matthias/scroll/prog/ceno6/poseidon) (*)
```

For now I've just whitelisted the existing offenders, but in the future
a new PR can work on shrinking that list.

---------

Co-authored-by: Zhang Zhuo <mycinbrin@gmail.com>