Fix a concurrency bug in the `mock_prover` (#343)
While investigating our tests, I got occasional failures like the
following:

```
        FAIL [   0.003s] ceno_zkvm scheme::mock_prover::tests::test_assert_zero_1

--- STDOUT:              ceno_zkvm scheme::mock_prover::tests::test_assert_zero_1 ---

running 1 test
test scheme::mock_prover::tests::test_assert_zero_1 ... FAILED

failures:

failures:
    scheme::mock_prover::tests::test_assert_zero_1

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 84 filtered out; finished in 0.00s

--- STDERR:              ceno_zkvm scheme::mock_prover::tests::test_assert_zero_1 ---
thread 'scheme::mock_prover::tests::test_assert_zero_1' panicked at ceno_zkvm/src/scheme/mock_prover.rs:291:49:
called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 5713)
stack backtrace:
   0:     0x5b31b75639c5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h83a98f6d5617789b
   1:     0x5b31b758a8ab - core::fmt::write::h880ae86840cfb66d
   2:     0x5b31b75612af - std::io::Write::write_fmt::h39b30cd087522a51
   3:     0x5b31b756379e - std::sys_common::backtrace::print::h5e0016a491d84c1d
   4:     0x5b31b7565119 - std::panicking::default_hook::{{closure}}::h0c2f75f7a65b5547
   5:     0x5b31b7564e5d - std::panicking::default_hook::h1284229a24b71c4c
   6:     0x5b31b75655b3 - std::panicking::rust_panic_with_hook::hca3ced3c46879131
   7:     0x5b31b7565494 - std::panicking::begin_panic_handler::{{closure}}::h4ff95bfaaee639b6
   8:     0x5b31b7563e89 - std::sys_common::backtrace::__rust_end_short_backtrace::h9ea6903d337d4498
   9:     0x5b31b75651c7 - rust_begin_unwind
  10:     0x5b31b728dd33 - core::panicking::panic_fmt::h766125e319de443c
  11:     0x5b31b728e1c6 - core::result::unwrap_failed::h942a9268418bbe17
  12:     0x5b31b7423e88 - once_cell::imp::OnceCell<T>::initialize::{{closure}}::hc1ee21766f98f3fc
  13:     0x5b31b753395c - once_cell::imp::initialize_or_wait::hdd8bf699e4c89212
  14:     0x5b31b7283792 - once_cell::imp::OnceCell<T>::initialize::hf44c7193bf21f43a
  15:     0x5b31b7477a67 - ceno_zkvm::scheme::mock_prover::MockProver<E>::run_maybe_challenge::hb12fdfee9f40754d
  16:     0x5b31b747a609 - ceno_zkvm::scheme::mock_prover::MockProver<E>::assert_satisfied::hcf9209e11d042a19
  17:     0x5b31b7480a22 - ceno_zkvm::scheme::mock_prover::tests::test_assert_zero_1::h1bb14ba97e93e8f6
  18:     0x5b31b749c809 - core::ops::function::FnOnce::call_once::he8a4303862ce2ecc
  19:     0x5b31b752688b - test::__rust_begin_short_backtrace::h0ba1545d31830bb8
  20:     0x5b31b7525f91 - test::run_test::{{closure}}::h4eaafd5cb0f565b7
  21:     0x5b31b74eeb64 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb0fbd81a33fa2097
  22:     0x5b31b74f3532 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1b2e25513f007c23
  23:     0x5b31b7569a9b - std::sys::pal::unix::thread::Thread::new::thread_start::haf9a58ee26566211
  24:     0x714a9d82639d - <unknown>
  25:     0x714a9d8ab49c - <unknown>
  26:                0x0 - <unknown>
  ```

As far as I can tell, this was caused by a [time-of-check to time-of-use (TOCTOU)](https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use)
issue in our code.  This PR fixes this.