Fix `no_mangle` (#398)
Clippy says:

```
     Compiling ceno_rt v0.1.0 (/home/matthias/scroll/prog/ceno/ceno_rt)
     Compiling examples v0.1.0 (/home/matthias/scroll/prog/ceno/examples)
  error: `#[no_mangle]` set on a function with the default (`Rust`) ABI
   --> examples/ceno_rt_mini.rs:7:1
    |
  7 | fn main() {}
    | ^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#no_mangle_with_rust_abi
    = note: `-D clippy::no-mangle-with-rust-abi` implied by `-D clippy::pedantic`
    = help: to override `-D clippy::pedantic` add `#[allow(clippy::no_mangle_with_rust_abi)]`
  help: set an ABI
    |
  7 | extern "C" fn main() {}
    | ++++++++++
  help: or explicitly set the default
    |
  7 | extern "Rust" fn main() {}
    | +++++++++++++
```

> # Why is this bad?

> The Rust ABI is not stable, but in many simple cases matches enough
with the C ABI that it is possible to forget to add extern "C" to a
function called from C. Changes to the Rust ABI can break this at any
point.

This PR fixes this problem.